version: "3.9"

services: 
  spa.fs.test.project:
    image: "node:18"
    ports:
      - "5173:5173"
    working_dir: /app
    networks:
      - fs-test-project
    entrypoint: /entrypoint.sh
    volumes:
      - ./frontend:/app
      - ./docker/spa/entrypoint.sh:/entrypoint.sh
    env_file: 
      - spa.dev.env